name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Force download of upload-artifact@v3
        uses: actions/upload-artifact@v3
        with:
          name: noop
          path: ./README.md  # ou un fichier existant quelconque

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: ./build
